### ISSUE TITLE
Possible wifi password leak

### ISSUE THREAD

**Issue by bagobor** [kirax999/Web-Shaker-ESP32-TMC2209#1]
Hi,

Thanks for sharing your project. I'm still learning esp32 and trying to build some projects with TMC2209 driver.
I've noticed that your published has some potentially sensitive information: 
wifi password and ssid 
https://github.com/kirax999/Web-Shaker-ESP32-TMC2209/blob/950c543949c25730f26da94e804e71a06bfd0fe8/Tumbler%20ESP32/src/main.cpp#L15

**Comment by kirax999** [comment]
it’s completely forgotten on my part, thank you for pointing it out
